### ISSUE TITLE
Toast Notifications

### ISSUE THREAD

**Issue by SoloJovian** [Saud-97/TachiyomiS97#11]
### Describe your suggested feature

Please reduce the number of notifications of Cloudflare bypass

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiS97 have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.3](https://github.com/saud-97/TachiyomiS97/releases/latest)**.
- [X] I have checked through the app settings for my feature.

**Comment by Saud-97** [comment]
Planned for next release.

**Comment by NikunjKhangwal** [comment]
Hello! Sorry for the off-topic question but i want to know if you're able to work consistently on the project now? I like the improvements in this app but i remember the development was paused for like 6 months in 2023 so i went back to J2K. Recent update came after 3 months as well. Ofc if you aren't, that's understandable too. I'm just asking out of curiosity. Thanks.

**Comment by Saud-97** [comment]
I never really stopped the development. Actually I only skipped those 6 months because the releases didn't have anything interesting to me to bring over. But then I decided to just stick to the same version as J2K so it would be easier for users to migrate and never miss any new update. So I'm willing to keep working on the app as I use it as my main app to watch stuff.

**Comment by NikunjKhangwal** [comment]
That makes sense and glad to know it'll continue. Guess I'll be switching again. Thanks again.
