### ISSUE TITLE
Add "data saver" option

### ISSUE THREAD

**Issue by Berserk0001** [Saud-97/TachiyomiS97#5]
### Describe your suggested feature

Can you add "data saver" featurefrom TachiyomiSy?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiS97 have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/saud-97/TachiyomiS97/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment]
I do not see the need for the data saver. Its sole purpose in TachiyomiSY iirc is to compress the image AFTER it got downloaded at full size. Therefore its only saving disk space but not bandwidth. 

If you want to regain space you have many options to clear disk space in the settings.

Also 
>  I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.

**Comment by Berserk0001** [comment]
Yes it does saves bandwith also....

**Comment by Berserk0001** [comment]
As you said that the image is downloaded then it gets compressed it is true but the image is downloaded on the server then compressed and gets downloaded on the device. As a result it saves more bandwith..

**Comment by Berserk0001** [comment]
To see the prove downloaded tachiSy and use data saver..
And enable download inducator on your device..

You will see tge difference...

**Comment by Berserk0001** [comment]
So I think data saver option is a good option if you implement on this app..

**Comment by Saud-97** [comment]
I think I forgot to reply here. I see your point, it does indeed save bandwitdh. 
Unfortunately I will not do it because the code base is very different than J2K base and I'm kinda busy. 
I think your best bet is requesting the feature from upstream or J2K and I will add it once J2K fork has it.
