### ISSUE TITLE
option to do someting to "Toast notifications" 

### ISSUE THREAD

**Issue by SoloJovian** [Saud-97/TachiyomiS97#7]
### Describe your suggested feature

As you have said that disabling the "toast notification" of Cloudflare will cause problems, I request you to do something about this issue . If you can, just disable the option while reading a chapter as it degrades the reading experience by some margin. 

### Other details

There is none.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiS97 have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.2](https://github.com/saud-97/TachiyomiS97/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment]
I'm thinking to reduce number of bypass attempts from 10 to 5 since most of the time (if it worked for that source anyways) it should work within 1 or 2 attempts. I will also reduce the toast time from 3.5 seconds to 2 seconds.

With these changes it should be less annoying.

**Comment by Saud-97** [comment]
> Don't some websites have rate limit?

The feature uses the extension preferences to connect to the source which can contain rate limits if applicable. Each attempt normally takes 30 seconds so every toast should show up in 30 seconds intervals and stay for 2 seconds.
