### ISSUE TITLE
holding Browse button opens up search ( with keyboard ). 

### ISSUE THREAD

**Issue by Sreinumder** [Saud-97/TachiyomiS97#8]
### Describe your suggested feature

Holding browse should open keyboard to search instead of default behaviour of opening extension list (which can already be opened by double tap).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiS97 have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.3](https://github.com/saud-97/TachiyomiS97/releases/latest)**.
- [X] I have checked through the app settings for my feature.

**Comment by Saud-97** [comment]
Will be added in next update.
